/**
 * scripts/tests/generate-agents-overview.test.js
 *
 * Tests for scripts/generate-agents-overview.js
 *
 * Acceptance Criteria verified:
 *   AC-05: Generator produces docs/agents-overview.md with all 42 personas,
 *          correct versions, correct suite grouping, and a generation timestamp.
 *   AC-06: `--check` exits 0 when the file is current, exits 1 when stale.
 */

import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import fs   from 'fs';
import path from 'path';
import { spawnSync } from 'child_process';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT      = path.resolve(__dirname, '..', '..');
const SCRIPT    = path.join(ROOT, 'scripts', 'generate-agents-overview.js');
const OUTPUT    = path.join(ROOT, 'docs', 'references', 'agents-overview.md');

// ─── Helpers ─────────────────────────────────────────────────────────────────

function countYamlFiles(dir) {
  return fs.readdirSync(dir).filter(file => file.endsWith('.yaml') && !file.startsWith('_')).length;
}

function suiteCounts() {
  const ledger = countYamlFiles(path.join(ROOT, 'personas', 'ledger', 'src', 'meta'));
  const standalone = countYamlFiles(path.join(ROOT, 'personas', 'standalone', 'src', 'meta'));
  const support = countYamlFiles(path.join(ROOT, 'personas', 'ledger-support', 'src', 'meta'));
  return { ledger, standalone, support, total: ledger + standalone + support };
}

function run(...args) {
  const result = spawnSync(process.execPath, [SCRIPT, ...args], {
    encoding: 'utf8',
    cwd: ROOT,
  });
  return {
    exitCode: result.status,
    stdout:   result.stdout ?? '',
    stderr:   result.stderr ?? '',
  };
}

// ─── AC-05: Generation correctness ───────────────────────────────────────────

describe('generate-agents-overview.js', () => {
  let content;

  beforeAll(() => {
    // Generate the file fresh to ensure test isolation
    const { exitCode } = run();
    if (exitCode !== 0) throw new Error('Generator exited non-zero during test setup');
    content = fs.readFileSync(OUTPUT, 'utf8');
  });

  it('writes docs/references/agents-overview.md', () => {
    expect(fs.existsSync(OUTPUT)).toBe(true);
  });

  it('includes a generation timestamp header', () => {
    expect(content).toMatch(/> \*\*Generated:\*\* \d{4}-\d{2}-\d{2}/);
  });

  it('reports the generated total persona count from the metadata sources', () => {
    const { total } = suiteCounts();
    expect(content).toContain(`**Total Personas:** ${total}`);
  });

  it('contains all three suite section headings', () => {
    expect(content).toContain('## Ledger Pipeline Personas');
    expect(content).toContain('## Standalone Personas');
    expect(content).toContain('## Ledger-Support Personas');
  });

  it('contains all 9 ledger pipeline personas', () => {
    for (let i = 1; i <= 9; i++) {
      expect(content, `Stage ${i} heading missing`).toMatch(new RegExp(`### Stage ${i} —`));
    }
  });

  it('contains identity lines for ledger personas', () => {
    expect(content).toContain('**Identity:** Chief Product Officer (CPO)');
    expect(content).toContain('**Identity:** Technical Program Manager (TPM)');
    expect(content).toContain('**Identity:** Staff Software Engineer');
  });

  it('contains inputs/outputs lines for ledger personas', () => {
    expect(content).toContain('- **Inputs:** Feature request, bug report, or task description from the user');
    expect(content).toContain('- **Outputs:** Structured plan document');
  });

  it('contains standalone persona headings', () => {
    expect(content).toContain('### AGENTS.md Curator');
    expect(content).toContain('### Developer — Standalone');
    expect(content).toContain('### Planner');
  });

  it('renders (Standalone) as — Standalone in headings', () => {
    expect(content).not.toContain('### Developer (Standalone)');
    expect(content).toContain('### Developer — Standalone');
  });

  it('contains use_when lines for standalone personas', () => {
    expect(content).toContain('- **Use When:**');
  });

  it('contains ledger-support persona headings', () => {
    expect(content).toContain('### Ledger Bootstrapper');
    expect(content).toContain('### Ledger Standalone Archiver');
  });

  it('contains the summary table with metadata-derived counts', () => {
    const { ledger, standalone, support, total } = suiteCounts();
    expect(content).toMatch(new RegExp(`\\| Ledger Pipeline \\| ${ledger} \\|`));
    expect(content).toMatch(new RegExp(`\\| Standalone \\| ${standalone} \\|`));
    expect(content).toMatch(new RegExp(`\\| Ledger-Support \\| ${support} \\|`));
    expect(content).toMatch(new RegExp(`\\| \\*\\*Total\\*\\* \\| \\*\\*${total}\\*\\* \\|`));
  });

  it('contains the generated-by comment header', () => {
    expect(content).toContain('<!-- Generated by scripts/generate-agents-overview.js');
  });

  it('preserves the companion link to workflow-and-ledger.md', () => {
    expect(content).toContain('[workflow-and-ledger.md](workflow-and-ledger.md)');
  });
});

// ─── AC-06: --check flag behavior ────────────────────────────────────────────

describe('--check flag', () => {
  it('exits 0 when the file is current', () => {
    // Run generator to ensure file is fresh
    run();
    const { exitCode, stdout } = run('--check');
    expect(exitCode).toBe(0);
    expect(stdout).toContain('up to date');
  });

  it('exits 1 when the output file does not exist', () => {
    const backup = fs.readFileSync(OUTPUT, 'utf8');
    fs.unlinkSync(OUTPUT);
    try {
      const { exitCode } = run('--check');
      expect(exitCode).toBe(1);
    } finally {
      fs.writeFileSync(OUTPUT, backup, 'utf8');
    }
  });

  it('exits 1 when the output file has been manually modified', () => {
    const original = fs.readFileSync(OUTPUT, 'utf8');
    // Simulate manual edit: remove a line
    fs.writeFileSync(OUTPUT, original + '\n<!-- manual edit -->\n', 'utf8');
    try {
      const { exitCode } = run('--check');
      expect(exitCode).toBe(1);
    } finally {
      // Restore clean file
      run();
    }
  });
});
